name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout next project repo
        uses: actions/checkout@v3
        with:
          repository: wdrik/next-project
          path: next-project

      - name: Install dependencies
        working-directory: ./next-project
        run: npm install

      - name: Build
        working-directory: ./next-project
        run: npm run build

      - name: Start
        working-directory: ./next-project
        run: npm run start & npx wait-on http://localhost:3000

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
